In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data) # 직접 생성
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# numpy arry <--> torch tensor 서로가 서로를 생성가능
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_ones)
print()
print(x_rand)

tensor([[1, 1],
        [1, 1]])

tensor([[0.9619, 0.0994],
        [0.2984, 0.8275]])


In [5]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.rand(shape)
zeros_tensor = torch.rand(shape)

print(f'Random Tensor: \n{rand_tensor}\n')
print(f'Random Tensor: \n{ones_tensor}\n')
print(f'Random Tensor: \n{zeros_tensor}\n')

Random Tensor: 
tensor([[0.7586, 0.0237, 0.9732],
        [0.1651, 0.2453, 0.3327]])

Random Tensor: 
tensor([[0.9671, 0.9708, 0.7869],
        [0.0480, 0.8457, 0.4544]])

Random Tensor: 
tensor([[0.2140, 0.9576, 0.2153],
        [0.1538, 0.2541, 0.0272]])



In [9]:
tensor = torch.rand(3,4)
print(tensor)
print(f'shpae of tensor: {tensor.shape}')
print(f'datatype of tensor: {tensor.dtype}')
print(f'device of tensor: {tensor.device}')

tensor([[0.4362, 0.6435, 0.6644, 0.2899],
        [0.3255, 0.8428, 0.5249, 0.4362],
        [0.8835, 0.5805, 0.9365, 0.4517]])
shpae of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu


In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f'Device tensor is stored on {tensor.device}')

Device tensor is stored on cuda:0


In [28]:
tensor = torch.ones(4,4)
print(tensor)
print()
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
t1 = torch.cat([tensor, tensor, tensor], dim= 1)
t2 = torch.stack([tensor, tensor, tensor], dim= 1)
print(t1)
print()
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [24]:
# element-wise mul
print(f'tensor.mul(tensor)\n {tensor.mul(tensor)}\n')
print(f'tensor * tensor\n {tensor * tensor}\n')
# matrix mul
print(f'tensor.matmul(tensor.T)\n {tensor.matmul(tensor.T)}\n')
print(f'tensor @ tensor.T\n {tensor @ tensor.T}\n')

tensor.mul(tensor)
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor.matmul(tensor.T)
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [29]:
# in-place: "_"
# 권장하지 않음
print(tensor,'\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [30]:
# tensor -> Numpy
t = torch.ones(5)
print(f't: {t}')
n =t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [31]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [33]:
# numpy -> tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
np.add(n,1,out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
