In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data) # 직접 생성
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# numpy arry <--> torch tensor 서로가 서로를 생성가능
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_ones)
print()
print(x_rand)

tensor([[1, 1],
        [1, 1]])

tensor([[0.9652, 0.8472],
        [0.2377, 0.1609]])
