In [1]:
import torch

torch.__version__

'1.11.0'

In [2]:
x = torch.empty(4,2)
print(x)

tensor([[3.2870e+21, 8.1341e+20],
        [8.2359e-10, 4.1536e-08],
        [6.8997e-07, 2.6555e-06],
        [8.3575e+20, 3.3502e-09]])


In [4]:
x = torch.rand(4,2)
print(x)

tensor([[0.9303, 0.4348],
        [0.7579, 0.0745],
        [0.7179, 0.2782],
        [0.0709, 0.1815]])


In [5]:
x = torch.zeros(4,2,dtype= torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [6]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])
