In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.2


In [3]:
# Tensor의 객체

# type: string, float etc
# shpape: demention of data
# Rank: number of demention

In [4]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [6]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [7]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


In [8]:
rand  = tf.random.uniform([1], 0,1)
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.425529], shape=(1,), dtype=float32)


In [9]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-0.32965112  2.777303  ]], shape=(1, 2), dtype=float32)


In [10]:
rand3 = tf.random.normal(shape=(3,2), mean = 0, stddev= 1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[ 0.17483193 -0.26503485]
 [-0.01578627 -0.7225121 ]
 [-2.1462183  -1.935933  ]], shape=(3, 2), dtype=float32)


In [11]:
# Eager Mode
a = tf.constant(3)
b = tf.constant(2)

In [12]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [13]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [14]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [15]:
c = tf.add(a,b).numpy()
print(type(c))

<class 'numpy.int32'>


In [16]:
c_sqaure = np.square(c,dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [17]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.,]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [18]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [19]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [20]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [21]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [22]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [23]:
# type 변환 `type이 다르면 계산 안됨`

In [24]:
a = tf.constant(2)
print(a)

b =  tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [25]:
try:
    a + b
except:
    print('Error')

print(a + tf.cast(b,tf.int32))

Error
tf.Tensor(4, shape=(), dtype=int32)


In [26]:
# Auto Graph

In [27]:
import timeit

In [28]:
@tf.function
def my_function(x):
    return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [30]:
def my_function_(x):
    return x**2 - 10*x +3

print(my_function_(2))
print(my_function_(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [31]:
tf_my_func = tf.function(my_function_)

print(tf_my_func)
print(tf_my_func(2))

tf.Tensor(-13, shape=(), dtype=int32)


In [32]:
tf_my_func.python_function(2)

-13

In [36]:
def function_to_get_faster(x,y,b):
    x = tf.matmul(x,y)
    x = x+b
    return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1 = tf.constant([[1.,2.]])
y1 = tf.constant([[2.],[3.]])
b1 = tf.constant(4.)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

array([[12.]], dtype=float32)

In [37]:
def inner_function(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.],[3.]])
    b = tf.constant(4.)
    return inner_function(x,y,b)

outer_function(tf.constant([[1.,2.]])).numpy()

array([[12.]], dtype=float32)

In [38]:
print(tf.autograph.to_code(my_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [39]:
X = tf.Variable(20.)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


In [ ]:
# AutoGrad

In [40]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

In [41]:
dy_dx = tape.gradient(y,x) # 한번만 가능
dy_dx.numpy()

6.0

In [42]:
x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y_sq = y**2
    z = x**2 + tf.stop_gradient(y_sq)

grad = tape.gradient(z, {'x':x,'y':y})

print('dz/dx:', grad['x'])
print('dz/dy:', grad['y'])

dz/dx: tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy: None


In [ ]:
# 신경망

In [43]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

def Neuron(x,W,bias=0):
    z = x + W +bias
    return sigmoid(z)

In [44]:
x = tf.random.normal((1,2),0,1)
W = tf.random.normal((1,2),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1, 2)
W.shape: (1, 2)
tf.Tensor([[0.35841498 1.5991813 ]], shape=(1, 2), dtype=float32)
tf.Tensor([[0.2965436 1.9704602]], shape=(1, 2), dtype=float32)
[[0.658127   0.97260565]]


In [45]:
x = tf.random.normal((2,1),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (2, 1)
W.shape: (2, 1)
tf.Tensor(
[[1.1442131 ]
 [0.48380256]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.5935764 ]
 [ 0.08290005]], shape=(2, 1), dtype=float32)
[[0.6342833]
 [0.638002 ]]


In [47]:
x = tf.random.normal((1,),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1,)
W.shape: (2, 1)
tf.Tensor([0.23364697], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.50418127]
 [-2.0430999 ]], shape=(2, 1), dtype=float32)
[[0.4327759 ]
 [0.14070426]]


In [ ]:
# 퍼셉트론
# w(next step) = (가중치) + (힉습룰)(정답 레이블 - 예측 레이블)x

In [48]:
x = 1
y = 0
W = tf.random.normal([1],0,1)
print(Neuron(x,W))
print('y:',y)

[0.69073844]
y: 0


In [49]:
for i in range(1000):
    output = Neuron(x,W)
    error = y - output
    W = W + x*0.1*error

    if i%100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[-0.11621329]	[0.11621329]
200	[-0.05603468]	[0.05603468]
300	[-0.03647276]	[0.03647276]
400	[-0.02693959]	[0.02693959]
500	[-0.02132544]	[0.02132544]
600	[-0.01763419]	[0.01763419]
700	[-0.0150256]	[0.0150256]
800	[-0.01308559]	[0.01308559]
900	[-0.01158708]	[0.01158708]
1000	[-0.01039516]	[0.01039516]


In [52]:
def Neuron2(x,W,bias = 0):
    z = tf.matmul(x,W, transpose_b=True) + bias
    return sigmoid(z)

In [53]:
x = tf.random.normal((1,3),0,1)
y = tf.ones(1)
W = tf.random.normal((1,3),0,1)

print(Neuron2(x,W))
print('y:',y)

[[0.00777639]]
y: tf.Tensor([1.], shape=(1,), dtype=float32)


In [54]:
for i in range(1000):
    output = Neuron2(x,W)
    error = y - output
    W = W + x * 0.1 * error

    if i % 100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[[0.02104908]]	[[0.9789509]]
200	[[0.00984114]]	[[0.99015886]]
300	[[0.00641155]]	[[0.99358845]]
400	[[0.00475234]]	[[0.99524766]]
500	[[0.00377464]]	[[0.99622536]]
600	[[0.00313038]]	[[0.9968696]]
700	[[0.00267375]]	[[0.99732625]]
800	[[0.00233328]]	[[0.9976667]]
900	[[0.00206971]]	[[0.9979303]]
1000	[[0.00185955]]	[[0.99814045]]


In [60]:
x = tf.random.normal((1,3),0,1)
weight = tf.random.normal((1,3),0,1)
bias = tf.zeros((1,1))

y = tf.ones((1,))

print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[0.34986046 0.11373322 1.2037851 ]]
weight	: [[ 0.5823509  -1.0463151   0.76085883]]
bias	: [[0.]]


In [61]:
for i in range(1000):
    output = Neuron2(x, weight,bias = bias)
    error = y - output
    weight = weight + x * 0.1 * error
    bias = bias + 1*0.1*error

    if i % 100 ==99:
        print("{}\t{}\t{}".format(i+1, error,output))

100	[[0.03663439]]	[[0.9633656]]
200	[[0.01902848]]	[[0.9809715]]
300	[[0.01281285]]	[[0.98718715]]
400	[[0.00964874]]	[[0.99035126]]
500	[[0.0077346]]	[[0.9922654]]
600	[[0.00645262]]	[[0.9935474]]
700	[[0.00553447]]	[[0.99446553]]
800	[[0.00484467]]	[[0.99515533]]
900	[[0.00430745]]	[[0.99569255]]
1000	[[0.00387734]]	[[0.99612266]]


In [62]:
print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[0.34986046 0.11373322 1.2037851 ]]
weight	: [[ 1.198167  -0.8461246  2.879734 ]]
bias	: [[1.7601761]]
