In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.2


In [3]:
# Tensor의 객체

# type: string, float etc
# shpape: demention of data
# Rank: number of demention

In [4]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [6]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [7]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


In [8]:
rand  = tf.random.uniform([1], 0,1)
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.600996], shape=(1,), dtype=float32)


In [9]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[0.6092713  0.30268526]], shape=(1, 2), dtype=float32)


In [10]:
rand3 = tf.random.normal(shape=(3,2), mean = 0, stddev= 1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[-0.16663936 -0.9651545 ]
 [-0.4177425  -0.27948734]
 [ 0.87869984 -1.0158862 ]], shape=(3, 2), dtype=float32)


In [11]:
# Eager Mode
a = tf.constant(3)
b = tf.constant(2)

In [12]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [13]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [14]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [15]:
c = tf.add(a,b).numpy()
print(type(c))

<class 'numpy.int32'>


In [16]:
c_sqaure = np.square(c,dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [17]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.,]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [18]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [19]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [20]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [21]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [22]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [23]:
# type 변환 `type이 다르면 계산 안됨`

In [24]:
a = tf.constant(2)
print(a)

b =  tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [25]:
try:
    a + b
except:
    print('Error')

print(a + tf.cast(b,tf.int32))

Error
tf.Tensor(4, shape=(), dtype=int32)


In [26]:
# Auto Graph

In [27]:
import timeit

In [28]:
@tf.function
def my_function(x):
    return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [29]:
def my_function_(x):
    return x**2 - 10*x +3

print(my_function_(2))
print(my_function_(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [30]:
tf_my_func = tf.function(my_function_)

print(tf_my_func)
print(tf_my_func(2))

tf.Tensor(-13, shape=(), dtype=int32)


In [31]:
tf_my_func.python_function(2)

-13

In [32]:
def function_to_get_faster(x,y,b):
    x = tf.matmul(x,y)
    x = x+b
    return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1 = tf.constant([[1.,2.]])
y1 = tf.constant([[2.],[3.]])
b1 = tf.constant(4.)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

array([[12.]], dtype=float32)

In [33]:
def inner_function(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.],[3.]])
    b = tf.constant(4.)
    return inner_function(x,y,b)

outer_function(tf.constant([[1.,2.]])).numpy()

array([[12.]], dtype=float32)

In [34]:
print(tf.autograph.to_code(my_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [35]:
X = tf.Variable(20.)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


In [36]:
# AutoGrad

In [37]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

In [38]:
dy_dx = tape.gradient(y,x) # 한번만 가능
dy_dx.numpy()

6.0

In [39]:
x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y_sq = y**2
    z = x**2 + tf.stop_gradient(y_sq)

grad = tape.gradient(z, {'x':x,'y':y})

print('dz/dx:', grad['x'])
print('dz/dy:', grad['y'])

dz/dx: tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy: None


In [40]:
# 신경망

In [41]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

def Neuron(x,W,bias=0):
    z = x + W +bias
    return sigmoid(z)

In [42]:
x = tf.random.normal((1,2),0,1)
W = tf.random.normal((1,2),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1, 2)
W.shape: (1, 2)
tf.Tensor([[ 0.5245128  -0.41554424]], shape=(1, 2), dtype=float32)
tf.Tensor([[0.40785816 0.07391325]], shape=(1, 2), dtype=float32)
[[0.71755606 0.41541335]]


In [43]:
x = tf.random.normal((2,1),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (2, 1)
W.shape: (2, 1)
tf.Tensor(
[[ 0.7399022 ]
 [-0.00224843]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.8063078]
 [-0.7953786]], shape=(2, 1), dtype=float32)
[[0.48340473]
 [0.31053334]]


In [44]:
x = tf.random.normal((1,),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1,)
W.shape: (2, 1)
tf.Tensor([-0.04664742], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.08689597]
 [ 0.19740511]], shape=(2, 1), dtype=float32)
[[0.46666366]
 [0.5376182 ]]


In [45]:
# 퍼셉트론
# w(next step) = (가중치) + (힉습룰)(정답 레이블 - 예측 레이블)x

In [46]:
x = 1
y = 0
W = tf.random.normal([1],0,1)
print(Neuron(x,W))
print('y:',y)

[0.26868257]
y: 0


In [47]:
for i in range(1000):
    output = Neuron(x,W)
    error = y - output
    W = W + x*0.1*error

    if i%100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[-0.08155527]	[0.08155527]
200	[-0.04612057]	[0.04612057]
300	[-0.03193031]	[0.03193031]
400	[-0.02435858]	[0.02435858]
500	[-0.0196675]	[0.0196675]
600	[-0.01648147]	[0.01648147]
700	[-0.01417856]	[0.01417856]
800	[-0.01243738]	[0.01243738]
900	[-0.01107524]	[0.01107524]
1000	[-0.00998088]	[0.00998088]


In [48]:
def Neuron2(x,W,bias = 0):
    z = tf.matmul(x,W, transpose_b=True) + bias
    return sigmoid(z)

In [49]:
x = tf.random.normal((1,3),0,1)
y = tf.ones(1)
W = tf.random.normal((1,3),0,1)

print(Neuron2(x,W))
print('y:',y)

[[0.5529299]]
y: tf.Tensor([1.], shape=(1,), dtype=float32)


In [50]:
for i in range(1000):
    output = Neuron2(x,W)
    error = y - output
    W = W + x * 0.1 * error

    if i % 100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[[0.17537516]]	[[0.82462484]]
200	[[0.10097575]]	[[0.89902425]]
300	[[0.06976056]]	[[0.93023944]]
400	[[0.05298078]]	[[0.9470192]]
500	[[0.04259437]]	[[0.9574056]]
600	[[0.03556162]]	[[0.9644384]]
700	[[0.03049582]]	[[0.9695042]]
800	[[0.02667856]]	[[0.97332144]]
900	[[0.02370155]]	[[0.97629845]]
1000	[[0.02131665]]	[[0.97868335]]


In [51]:
x = tf.random.normal((1,3),0,1)
weight = tf.random.normal((1,3),0,1)
bias = tf.zeros((1,1))

y = tf.ones((1,))

print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[-1.0508274 -0.6953251  1.0884959]]
weight	: [[-0.07275822  0.4582829  -0.74206555]]
bias	: [[0.]]


In [52]:
for i in range(1000):
    output = Neuron2(x, weight,bias = bias)
    error = y - output
    weight = weight + x * 0.1 * error
    bias = bias + 1*0.1*error

    if i % 100 ==99:
        print("{}\t{}\t{}".format(i+1, error,output))

100	[[0.0287776]]	[[0.9712224]]
200	[[0.01391399]]	[[0.986086]]
300	[[0.00915319]]	[[0.9908468]]
400	[[0.00681502]]	[[0.993185]]
500	[[0.0054267]]	[[0.9945733]]
600	[[0.00450766]]	[[0.99549234]]
700	[[0.00385439]]	[[0.9961456]]
800	[[0.00336629]]	[[0.9966337]]
900	[[0.00298786]]	[[0.99701214]]
1000	[[0.00268584]]	[[0.99731416]]


In [53]:
print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[-1.0508274 -0.6953251  1.0884959]]
weight	: [[-2.01368   -0.8260105  1.2684294]]
bias	: [[1.8470418]]


In [ ]:
# Gate

In [ ]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
Y = np.array([[1],[0],[0],[0]])

W = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    