In [2]:
import numpy as np
import tensorflow as tf

In [3]:
print(tf.__version__)

2.8.0


In [4]:
# Tensor의 객체

# type: string, float etc
# shpape: demention of data
# Rank: number of demention

In [5]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [6]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [7]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [8]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


In [9]:
rand  = tf.random.uniform([1], 0,1)
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.3077228], shape=(1,), dtype=float32)


In [10]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-1.9871453   0.09353577]], shape=(1, 2), dtype=float32)


In [11]:
rand3 = tf.random.normal(shape=(3,2), mean = 0, stddev= 1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[0.11941846 0.5460316 ]
 [1.2759687  0.1134923 ]
 [1.033591   0.9624208 ]], shape=(3, 2), dtype=float32)


In [12]:
# Eager Mode
a = tf.constant(3)
b = tf.constant(2)

In [13]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [14]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [15]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [16]:
c = tf.add(a,b).numpy()
print(type(c))

<class 'numpy.int32'>


In [17]:
c_sqaure = np.square(c,dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [18]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.,]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [19]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [20]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [21]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [22]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [23]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [24]:
# type 변환 `type이 다르면 계산 안됨`

In [25]:
a = tf.constant(2)
print(a)

b =  tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [26]:
try:
    a + b
except:
    print('Error')

print(a + tf.cast(b,tf.int32))

Error
tf.Tensor(4, shape=(), dtype=int32)


In [27]:
# Auto Graph

In [28]:
import timeit

In [29]:
@tf.function
def my_function(x):
    return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [30]:
def my_function_(x):
    return x**2 - 10*x +3

print(my_function_(2))
print(my_function_(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [31]:
tf_my_func = tf.function(my_function_)

print(tf_my_func)
print(tf_my_func(2))

tf.Tensor(-13, shape=(), dtype=int32)


In [32]:
tf_my_func.python_function(2)

-13

In [33]:
def function_to_get_faster(x,y,b):
    x = tf.matmul(x,y)
    x = x+b
    return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1 = tf.constant([[1.,2.]])
y1 = tf.constant([[2.],[3.]])
b1 = tf.constant(4.)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

array([[12.]], dtype=float32)

In [34]:
def inner_function(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.],[3.]])
    b = tf.constant(4.)
    return inner_function(x,y,b)

outer_function(tf.constant([[1.,2.]])).numpy()

array([[12.]], dtype=float32)

In [35]:
print(tf.autograph.to_code(my_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = (((ag__.ld(x) ** 2) - (10 * ag__.ld(x))) + 3)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [36]:
X = tf.Variable(20.)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


In [37]:
# AutoGrad

In [38]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

In [39]:
dy_dx = tape.gradient(y,x) # 한번만 가능
dy_dx.numpy()

6.0

In [40]:
x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y_sq = y**2
    z = x**2 + tf.stop_gradient(y_sq)

grad = tape.gradient(z, {'x':x,'y':y})

print('dz/dx:', grad['x'])
print('dz/dy:', grad['y'])

dz/dx: tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy: None


In [41]:
# 신경망

In [42]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

def Neuron(x,W,bias=0):
    z = x + W +bias
    return sigmoid(z)

In [43]:
x = tf.random.normal((1,2),0,1)
W = tf.random.normal((1,2),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1, 2)
W.shape: (1, 2)
tf.Tensor([[ 0.26796615 -1.3974209 ]], shape=(1, 2), dtype=float32)
tf.Tensor([[0.38973722 0.3600906 ]], shape=(1, 2), dtype=float32)
[[0.6587443  0.26166543]]


In [44]:
x = tf.random.normal((2,1),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (2, 1)
W.shape: (2, 1)
tf.Tensor(
[[ 0.32988295]
 [-0.44985643]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[2.3206108 ]
 [0.20503363]], shape=(2, 1), dtype=float32)
[[0.9340414 ]
 [0.43909824]]


In [45]:
x = tf.random.normal((1,),0,1)
W = tf.random.normal((2,1),0,1)

print('x.shape:', x.shape)
print('W.shape:', W.shape)

print(x)
print(W)

print(Neuron(x,W))

x.shape: (1,)
W.shape: (2, 1)
tf.Tensor([0.0696428], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.32544768]
 [-2.0399024 ]], shape=(2, 1), dtype=float32)
[[0.43639523]
 [0.122361  ]]


In [46]:
# 퍼셉트론
# w(next step) = (가중치) + (힉습룰)(정답 레이블 - 예측 레이블)x

In [47]:
x = 1
y = 0
W = tf.random.normal([1],0,1)
print(Neuron(x,W))
print('y:',y)

[0.93657416]
y: 0


In [48]:
for i in range(1000):
    output = Neuron(x,W)
    error = y - output
    W = W + x*0.1*error

    if i%100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[-0.15065862]	[0.15065862]
200	[-0.06360946]	[0.06360946]
300	[-0.03961068]	[0.03961068]
400	[-0.028632]	[0.028632]
500	[-0.02237861]	[0.02237861]
600	[-0.01835102]	[0.01835102]
700	[-0.01554428]	[0.01554428]
800	[-0.01347804]	[0.01347804]
900	[-0.01189424]	[0.01189424]
1000	[-0.01064199]	[0.01064199]


In [49]:
def Neuron2(x,W,bias = 0):
    z = tf.matmul(x,W, transpose_b=True) + bias
    return sigmoid(z)

In [50]:
x = tf.random.normal((1,3),0,1)
y = tf.ones(1)
W = tf.random.normal((1,3),0,1)

print(Neuron2(x,W))
print('y:',y)

[[0.7141642]]
y: tf.Tensor([1.], shape=(1,), dtype=float32)


In [51]:
for i in range(1000):
    output = Neuron2(x,W)
    error = y - output
    W = W + x * 0.1 * error

    if i % 100 == 99:
        print('{}\t{}\t{}'.format(i+1,error,output))

100	[[0.06357002]]	[[0.93643]]
200	[[0.03428566]]	[[0.96571434]]
300	[[0.02334338]]	[[0.9766566]]
400	[[0.01766336]]	[[0.98233664]]
500	[[0.01419479]]	[[0.9858052]]
600	[[0.01185966]]	[[0.98814034]]
700	[[0.01018149]]	[[0.9898185]]
800	[[0.00891793]]	[[0.9910821]]
900	[[0.00793242]]	[[0.9920676]]
1000	[[0.00714254]]	[[0.99285746]]


In [52]:
x = tf.random.normal((1,3),0,1)
weight = tf.random.normal((1,3),0,1)
bias = tf.zeros((1,1))

y = tf.ones((1,))

print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[ 0.21929647  0.03758995 -0.7430791 ]]
weight	: [[-0.20523676  0.97213215 -0.02449946]]
bias	: [[0.]]


In [53]:
for i in range(1000):
    output = Neuron2(x, weight,bias = bias)
    error = y - output
    weight = weight + x * 0.1 * error
    bias = bias + 1*0.1*error

    if i % 100 ==99:
        print("{}\t{}\t{}".format(i+1, error,output))

100	[[0.0650422]]	[[0.9349578]]
200	[[0.03255159]]	[[0.9674484]]
300	[[0.02157605]]	[[0.97842395]]
400	[[0.01610571]]	[[0.9838943]]
500	[[0.01283783]]	[[0.9871622]]
600	[[0.01066792]]	[[0.9893321]]
700	[[0.00912327]]	[[0.99087673]]
800	[[0.00796807]]	[[0.99203193]]
900	[[0.00707179]]	[[0.9929282]]
1000	[[0.00635624]]	[[0.99364376]]


In [54]:
print('x\t: {}\nweight\t: {}\nbias\t: {}'.format(x,weight,bias))

x	: [[ 0.21929647  0.03758995 -0.7430791 ]]
weight	: [[ 0.4852672  1.0904936 -2.3642476]]
bias	: [[3.148721]]


In [55]:
# Gate

In [56]:
X = np.array([[1,1],[1,0],[0,1],[0,0]])
Y = np.array([[1],[0],[0],[0]])

W = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    

SyntaxError: unexpected EOF while parsing (814109163.py, line 9)