In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.6.2


In [4]:
# Tensor의 객체

# type: string, float etc
# shpape: demention of data
# Rank: number of demention

In [5]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [6]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [7]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [8]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


In [9]:
rand  = tf.random.uniform([1], 0,1)
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.82095313], shape=(1,), dtype=float32)


In [10]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[ 0.48676246 -1.7496558 ]], shape=(1, 2), dtype=float32)


In [11]:
rand3 = tf.random.normal(shape=(3,2), mean = 0, stddev= 1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[ 0.02106778 -1.8647584 ]
 [ 1.0038146  -0.5060433 ]
 [ 2.1510806   1.1032761 ]], shape=(3, 2), dtype=float32)


In [12]:
# Eager Mode
a = tf.constant(3)
b = tf.constant(2)

In [13]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [14]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [15]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [16]:
c = tf.add(a,b).numpy()
print(type(c))

<class 'numpy.int32'>


In [17]:
c_sqaure = np.square(c,dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [19]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.,]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [20]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [21]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [22]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [23]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [24]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
# type 변환 `type이 다르면 계산 안됨`

In [25]:
a = tf.constant(2)
print(a)

b =  tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [30]:
try:
    a + b
except:
    print('Error')

print(a + tf.cast(b,tf.int32))

Error
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# Auto Graph

In [31]:
import timeit

In [32]:
@tf.function
def my_function(x):
    return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)
